JOB/urls.py
from django.urls import path
from .views import *

app_name = 'job'

urlpatterns = [
    path('all-jobs',all_jobs,name='jobs'),
    path('job/<slug>/',get_job,name='job'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('JOB.urls',namespace='all-jobs')),
]

JOB/models.py
from django.db import models

# Create your models here.

Job_Type = (('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Intetship', 'Intetship'))

class job(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=1000,null=True)
    salary = models.IntegerField(default=1)
    location = models.CharField(max_length=10000,null=True)
    type = models.CharField(choices = Job_Type, max_length=20,default='Full Time')
    slug = models.SlugField()
    

JOB/views.py
from django.shortcuts import render
from .models import *

# Create your views here.

def all_jobs(request):
    all = job.objects.all()
    context = {'jobs': all}
    return render(request,'jobs/index.html',context)

def get_job(request,slug):
    single_job = job.objects.get(slug=slug)
    context = {'job':single_job}
    return render(request,'jobs/single_job.html',context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet" />
    <title>Job listing</title>
  </head>
  <body>
    <header>
      <nav>
        <div class="container">
          <div class="logo">
            <img src="{% static 'images/logo.svg' %}" alt="" />
          </div>
          <div class="links">
            <a href="{% url 'all-jobs:jobs' %}" onclick="menu()">Home</a>
          </div>
          <span class="material-icons menu" onclick="menu()">menu</span>
        </div>
      </nav>
    </header>
    {% block content %}

    {% endblock %}

    <script src="{% static 'app.js' %}"></script>
  </body>
</html>

templates/jobs/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <!-- job post lists -->
  <section>
    <div class="container">
      <!-- job post -->

      {% for job in jobs %}
        <div class="post">
          <!-- title and des -->
          <div class="job-info">
            <h1 class="job-title">{{job.title}}</h1>
            <div class="job-des">
              <div class="location item">
                <span class="material-icons">place</span>
                <p>{{job.location}}</p>
              </div>
              <div class="budget item">
                <span class="material-icons">attach_money</span>
                <p>{{job.salary}}/Pm</p>
              </div>
              <div class="time item">
                <span class="material-icons">schedule</span>
                <p>{{job.type}}</p>
              </div>
            </div>
          </div>
          <div class="buttons">
            <button class="apply"><a href="{% url 'all-jobs:job' job.slug %}">View Job</a></button>
          </div>
        </div>
        <!-- job post end -->
      {% endfor %}
    </div>
  </section>
{% endblock %}

templates/jobs/single_job.html
{% extends 'base.html' %}

{% block content %}
  <section>
    <div class="container">
      <div class="view-post">
        <h1 class="jobtitle">{{job.title}}</h1>
        <p class="location it">
          Location: <span>{{job.location}}</span>
        </p>
        <p class="status it">
          Type: <span>{{job.type}}</span>
        </p>
        <p class="budget it">
          Salary: <span>{{job.salary}}$</span>
        </p>
        <div class="desc">
          <p class="details">{{job.description}}</p>
        </div>
      </div>
    </div>
  </section>
{% endblock %}